module Binpacker
  def key: () -> [untyped, String]
  class TestDiscovery
    def initialize: (untyped) -> void
    def enumerate: () -> Array[Binpacker::Test]
  end
  class RSpecDiscovery < TestDiscovery
    def enumerate: () -> Array[Binpacker::Test]
  end
  class MinitestDiscovery < TestDiscovery
    def enumerate: () -> Array[Binpacker::Test]
  end
  class Test
  end
end
