module Binpacker
  class Timing
    def initialize: (untyped) -> void
    def calibrated?: () -> bool
    def load_raw: () -> (Hash[[String, untyped], untyped] | {})
    def load_per_file: () -> (Hash[String, untyped] | {})
    def normalize_path: (untyped) -> String
    def measured?: (file: untyped, name: untyped) -> bool
    def compact!: () -> nil
    def append_all: (untyped) -> nil
    class Entry
    end
  end
end
