module Binpacker
  class Timing
    def initialize: (untyped) -> void
    def load_raw: () -> (Hash[[String, untyped], untyped] | {})
    def load_per_file: () -> (Hash[String, untyped] | {})
    def normalize_path: (untyped) -> String
    class Entry
    end
  end
end
